//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ynventory.Backend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ynventory.Backend.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; does already exist.
        /// </summary>
        internal static string Error_EntityAlreadyExists {
            get {
                return ResourceManager.GetString("Error_EntityAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with id {1} is invalid: {2}.
        /// </summary>
        internal static string Error_EntityIllegalState {
            get {
                return ResourceManager.GetString("Error_EntityIllegalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with Id {1} does not exist.
        /// </summary>
        internal static string Error_EntityNotFound {
            get {
                return ResourceManager.GetString("Error_EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid.
        /// </summary>
        internal static string Error_InvalidPassword {
            get {
                return ResourceManager.GetString("Error_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calling Scryfall API: {0}.
        /// </summary>
        internal static string Error_Scryfall_ApiError {
            get {
                return ResourceManager.GetString("Error_Scryfall_ApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card with id {0} could not be found in the Scryfall API.
        /// </summary>
        internal static string Error_Scryfall_CardNotFound {
            get {
                return ResourceManager.GetString("Error_Scryfall_CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with name {0} does already exist.
        /// </summary>
        internal static string Error_UserAlreadyExists {
            get {
                return ResourceManager.GetString("Error_UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id {0} does not exist.
        /// </summary>
        internal static string Error_UserIdNotFound {
            get {
                return ResourceManager.GetString("Error_UserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with name {0} does not exist.
        /// </summary>
        internal static string Error_UserNameNotFound {
            get {
                return ResourceManager.GetString("Error_UserNameNotFound", resourceCulture);
            }
        }
    }
}
